branches:
  only:
    - master

sudo: required

os:
  - linux

language: generic

env:
- PY=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - gcc-5
    - g++-5

install:
  - echo "Building python environment...";
  - wget "https://repo.continuum.io/miniconda/Miniconda${PY:0:1}-4.7.12.1-Linux-x86_64.sh" -O miniconda.sh;
  - chmod +x miniconda.sh;
  - ./miniconda.sh -b  -p $HOME/miniconda;
  - export PATH=$HOME/miniconda/bin:$PATH;

  - conda create --yes -n PY$PY python=$PY;
  - source $HOME/miniconda/bin/activate PY$PY;

  - conda install --yes numpy scipy swig matplotlib

  - pip install --upgrade pip;
  - pip install openmdao==3.3

#  - git clone https://github.com/OpenMDAO/pyoptsparse.git;
  - git clone https://github.com/mdolab/pyoptsparse.git;
  - cd pyoptsparse;
  - python setup.py install;
  - cd ..;

  # display summary of installed packages and their versions
  - conda list

script:
  - python ssbj_mdf.py
  - python ssbj_idf.py
  - mkdir files
  - python ssbj_co.py
#  - python ssbj_bliss2000.py